docker_image: "quay.io/condaforge/linux-anvil-cos7-x86_64:latest"
env_name: "2024-2.2-py310-tiled"
conda_env_file: "env-py310.yml"
conda_binary: "mamba"
python_version: "3.10"
pkg_name: ""
pkg_version: ""
extra_packages: "mamba"
channels: "-c conda-forge"
extra_cmd_before_install: "yum install mesa-libGL -y"
extra_cmd_after_install: "conda remove perl --force -y"
docker_upload:
  - ghcr
  - dockerhub
  # - quay
zenodo_upload: "no"
zenodo_metadata:
  metadata:
    title: "NSLS-II collection conda environment"
    upload_type: "software"
    description: "NSLS-II collection conda environment"
    version: 2024-2.2-tiled
    creators:
      - name: Rakitin, Max
        affiliation: "Brookhaven National Laboratory"
      - name: Bischof, Garrett
        affiliation: "Brookhaven National Laboratory"
